from __future__ import annotations

MODULES: dict[str, dict[str, str]] = {
    "site": {"label": "Sito SPES", "icon": "🌐", "url": "https://www.spesginnasticamestre.it", "group": "Servizi"},
    "sportivi": {"label": "Sportivi in Cloud", "icon": "☁️", "url": "https://www.cloud32.it/GES/home", "group": "Servizi"},
    "wellness": {"label": "Wellness in Cloud", "icon": "💪", "url": "https://new.wellness.incloud.it/dashboard", "group": "Servizi"},
    "cassa_cloud": {"label": "Cassa in Cloud", "icon": "🧾", "url": "https://fo.cassanova.com/#/dashboard", "group": "Servizi"},
    "spes_connect": {"label": "SPES Connect", "icon": "🔗", "url": "https://connect.spesginnasticamestre.it/dashboard", "group": "Servizi"},
    "gmail_admin": {"label": "Gmail Amministrazione", "icon": "✉️", "url": "https://mail.google.com/", "group": "Comunicazione"},
    "gmail_segreteria": {"label": "Gmail Segreteria", "icon": "✉️", "url": "https://mail.google.com/", "group": "Comunicazione"},
    "gmail_consiglio": {"label": "Gmail Consiglio", "icon": "✉️", "url": "https://mail.google.com/", "group": "Comunicazione"},
    "pec": {"label": "PEC SPES", "icon": "📨", "url": "https://idp.infocert.it/login?clientName=legalmail_webmail_2023_i4", "group": "Comunicazione"},
    "drive": {"label": "Drive SPES", "icon": "☁️", "url": "https://drive.google.com/drive/u/4/home", "group": "Comunicazione"},
    "homebank_volksbank": {"label": "Volksbank", "icon": "🏦", "url": "https://cobaweb.volksbank.it/", "group": "Home Banking", "sensitive": "true"},
    "homebank_bcc": {"label": "BCC", "icon": "🏦", "url": "https://www.relaxbanking.it/v3/relaxbanking/", "group": "Home Banking", "sensitive": "true"},
    "homebank_nexi": {"label": "Nexi", "icon": "💳", "url": "https://business.nexi.it/login-business", "group": "Home Banking", "sensitive": "true"},
    "banking": {"label": "Riconciliazione bancaria", "icon": "💶", "action": "desktop-only", "group": "Amministrazione", "sensitive": "true"},
    "compensation": {"label": "Convertitore compensi", "icon": "🧮", "action": "desktop-only", "group": "Amministrazione"},
    "cash": {"label": "Gestione Cassa", "icon": "💰", "action": "desktop-only", "group": "Amministrazione", "sensitive": "true"},
    "csv_archive": {"label": "Archivio CSV", "icon": "📂", "action": "desktop-only", "group": "Amministrazione", "sensitive": "true"},
    "fgi_results": {"label": "Risultati FGI", "icon": "🏅", "action": "fgi-results", "group": "FGI"},
    "fgi_calendar": {"label": "Calendario gare", "icon": "📅", "action": "fgi-calendar", "group": "FGI"},
    "fgi_regulation": {"label": "Regolamento FGI", "icon": "📘", "action": "fgi-regulation", "group": "FGI"},
    "music_gare": {"label": "Musica per gare", "icon": "🎵", "url": "https://open.spotify.com/playlist/43fGlA3pU5xsLSRbYg9198", "group": "Musica"},
    "music_awards": {"label": "Musica premiazioni", "icon": "🏆", "url": "https://open.spotify.com/playlist/0QjHGc2S4ggUNNjQTXlENa", "group": "Musica"},
    "users_manage": {"label": "Utenti e permessi", "icon": "👥", "action": "users", "group": "Sistema", "sensitive": "true"},
    "activity_logs": {"label": "Registro attività", "icon": "📝", "action": "logs", "group": "Sistema", "sensitive": "true"},
    "backup": {"label": "Backup", "icon": "☁️", "action": "backup", "group": "Sistema", "sensitive": "true"},
    "updates": {"label": "Aggiornamenti", "icon": "🔄", "action": "updates", "group": "Sistema"},
}
